---
feeds:
- https://aws.amazon.com/blogs/security/feed/
- https://www.phoronix.com/rss.php
- https://www.zdnet.com/topic/security/rss.xml

# Optionally define an application to view the feeds
#externalViewer: firefox
# Optionally define args for the external viewer
#externalViewerArgs:
    #- --new-window
