---
feeds:
- https://news.ycombinator.com/rss
- https://www.reddit.com/r/golang/.rss
- https://www.reddit.com/r/linux/.rss
- https://www.zdnet.com/topic/security/rss.xml
- https://aws.amazon.com/blogs/security/feed/
- https://www.archlinux.org/feeds/news/

# Optionally define an an external application viewer
#externalViewer: firefox
